kind: Deployment 
apiVersion: apps/v1 
metadata: 
  name: airflow-scheduler 
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
      deploy: airflow
      component: scheduler
  template:
    metadata:
      labels:
        app: airflow
        deploy: airflow
        component: scheduler
    spec:
      containers:
        - name: airflow-scheduler
          image: apache/airflow:2.2.4
          imagePullPolicy: IfNotPresent
          env:
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              valueFrom:
                secretKeyRef:
                  name: airflow-config
                  key: sql_alchemy_conn
            - name: AIRFLOW__CORE__EXECUTOR
              valueFrom:
                secretKeyRef:
                  name: airflow-config
                  key: executor
          ports:
            - containerPort: 8080
          command: 
            - airflow 
          args:
            - scheduler