kind: Deployment 
apiVersion: apps/v1 
metadata: 
  name: airflow-initdb 
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
      deploy: airflow
      component: initdb
  template:
    metadata:
      labels:
        app: airflow
        deploy: airflow
        component: initdb
    spec:
      containers:
        - name: airflow-initdb
          image: apache/airflow:2.2.4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          command: 
            - airflow 
          args:
            - initdb