apiVersion: v1 
kind: ConfigMap 
metadata: 
  name: airflow-config
  namespace: airflow
  labels: 
    app: airflow 
data: 
  sql_alchemy_conn: "postgresql://admin:test123.@postgres:5432/postgresdb"
  executor: "KubernetesExecutor"