apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: airflow
  name: airflow-sa
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: airflow-role-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: airflow-sa
    namespace: default
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io