kind: Deployment 
apiVersion: apps/v1 
metadata: 
  name: airflow-scheduler 
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
      deploy: airflow
      component: scheduler
  template:
    metadata:
      labels:
        app: airflow
        deploy: airflow
        component: scheduler
    spec:
      containers:
        - name: airflow-scheduler
          image: ghcr.io/tuancamtbtx/airflow:main
          imagePullPolicy: IfNotPresent
          env:
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              valueFrom:
                configMapKeyRef:
                  name: airflow-config
                  key: sql_alchemy_conn
            - name: AIRFLOW__CORE__EXECUTOR
              valueFrom:
                configMapKeyRef:
                  name: airflow-config
                  key: executor
          command: 
            - tini
            - --
            - sh 
            - -c
            - airflow scheduler
      restartPolicy: Always
