apiVersion: v1
kind: Pod
metadata:
  labels:
    component: airflow-task
spec:
  containers:
    - args: []
      command: []
      env:
        - name: AIRFLOW__CORE__EXECUTOR
          value: LocalExecutor
        - name: AIRFLOW_HOME
          value: /home/airflow/airflow
        - name: AIRFLOW__CORE__DAGS_FOLDER
          value: /home/airflow/dags
        - name: IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      envFrom:
        - configMapRef:
            name: airflow-config
        - secretRef:
            name: airflow-secrets
        - secretRef:
            name: airflow-secrets-env
      image: "ghcr.io/tuancamtbtx/airflow:main"
      imagePullPolicy: IfNotPresent
      name: base
      resources:
        limits:
          cpu: "1"
          memory: 1000Mi
        requests:
          cpu: 200m
          memory: 200Mi
      volumeMounts:
        - mountPath: /airflow/home/dags
          name: airflow-dags
          readOnly: false
          subPath: dags
        - mountPath: /home/airflow/airflow/logs
          name: airflow-logs
          subPath: logs
          readOnly: false
        - mountPath: /home/airflow/airflow/airflow.cfg
          name: airflow-config
          readOnly: true
          subPath: airflow.cfg
        - mountPath: /.secrets
          name: gcp-logs-creds
          readOnly: true
  imagePullSecrets:
    - name: tiki-gcr
  restartPolicy: Never
  securityContext:
    fsGroup: 1000
    runAsUser: 1000
  serviceAccountName: sherlock
  volumes:
    - name: airflow-dags
      persistentVolumeClaim:
        claimName: airflow-dags
    - name: airflow-logs
      persistentVolumeClaim:
        claimName: airflow-logs
    - configMap:
        name: airlock-configmap
      name: airflow-config
  tolerations:
    - effect: NoSchedule
      key: dedicated
      operator: Equal
      value: preempt-8-32
    - effect: NoSchedule
      key: dedicated
      operator: Equal
      value: preempt-highmem
    - effect: NoSchedule
      key: dedicated
      operator: Equal
      value: np-6-39
