kind: Deployment 
apiVersion: apps/v1 
metadata: 
  name: kafkaconnect 
  namespace: dataplatform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafkaconnect
      deploy: kafkaconnect
      component: kafkaconnect