apiVersion: v1 
kind: ConfigMap 
metadata: 
  name: postgres-config
  namespace: airflow 
  labels: 
    app: postgres 
data: 
  POSTGRES_DB: postgresdb 
  POSTGRES_USER: admin 
  POSTGRES_PASSWORD: test123.